version: 2.1
jobs:
  one:
    docker:
      - image: alpine:3.15
        auth:
          username: rathorep
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout
      - run:
          name: The First Step
          command: |
            echo 'Hello World!'
            echo 'set the environment variable'
  two:
    docker:
      - image: nginx:latest
    steps:         
      - run: 
          name: The second step
          command: |
            ls -lrt
            
workflows: 
  version: 2
  pavan:
    jobs: 
      - one:
          filters:
            branches:
              only:
                - master
      - hold: 
          type: approval
          requires:
            - one
      - two:
          requires:
            - hold

      
          

            
            
