version: 2.1

parameters:
  image_tag:
    type: string
    default: "casestudy1"
  branch_name:
    type: string
    default: "main"  

jobs:
  build:
    machine:
      image: ubuntu-2004:current
    steps:
      - checkout
      - run:
          name: The First Step
          command: |
            echo "Hello World! - << pipeline.parameters.image_tag >>"
            echo "the value of branch name is - << pipeline.parameters.branch_name >>"



      
          

            
            
