version: 2.1
jobs:
  build:
    docker:
      - image: alpine:3.15
        auth:
          username: rathorep
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - run:
          name: The First Step
          command: |
            echo 'Hello World!'
            echo 'set the environment variable'
